// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Addresses struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Line1     string             `json:"line1"`
	Line2     pgtype.Text        `json:"line2"`
	City      string             `json:"city"`
	State     string             `json:"state"`
	Pincode   string             `json:"pincode"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrderItems struct {
	ID              pgtype.UUID    `json:"id"`
	OrderID         pgtype.UUID    `json:"order_id"`
	VariantID       pgtype.UUID    `json:"variant_id"`
	Quantity        int32          `json:"quantity"`
	PriceAtPurchase pgtype.Numeric `json:"price_at_purchase"`
}

type Orders struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AddressID       pgtype.UUID        `json:"address_id"`
	Status          string             `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	RazorpayOrderID string             `json:"razorpay_order_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Payments struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	RazorpayPaymentID string             `json:"razorpay_payment_id"`
	RazorpaySignature string             `json:"razorpay_signature"`
	Status            string             `json:"status"`
	Amount            pgtype.Numeric     `json:"amount"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
}

type ProductVariants struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	VariantName   string             `json:"variant_name"`
	StockQuantity int32              `json:"stock_quantity"`
	Sku           string             `json:"sku"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Products struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Images      []string           `json:"images"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Shipments struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	CourierName    string             `json:"courier_name"`
	TrackingNumber string             `json:"tracking_number"`
	Status         string             `json:"status"`
	ShippedAt      pgtype.Timestamptz `json:"shipped_at"`
}

type Users struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
