// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one

INSERT INTO addresses (user_id, line1, line2, city, state, pincode, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, line1, line2, city, state, pincode, is_default, created_at
`

type CreateAddressParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Line1     string      `json:"line1"`
	Line2     pgtype.Text `json:"line2"`
	City      string      `json:"city"`
	State     string      `json:"state"`
	Pincode   string      `json:"pincode"`
	IsDefault bool        `json:"is_default"`
}

// ============================================================================
// Addresses
// ============================================================================
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Addresses, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.IsDefault,
	)
	var i Addresses
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (user_id, address_id, status, total_amount, razorpay_order_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, address_id, status, total_amount, razorpay_order_id, created_at
`

type CreateOrderParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	AddressID       pgtype.UUID    `json:"address_id"`
	Status          string         `json:"status"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	RazorpayOrderID string         `json:"razorpay_order_id"`
}

// ============================================================================
// Orders & OrderItems
// ============================================================================
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.AddressID,
		arg.Status,
		arg.TotalAmount,
		arg.RazorpayOrderID,
	)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressID,
		&i.Status,
		&i.TotalAmount,
		&i.RazorpayOrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, variant_id, quantity, price_at_purchase)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, variant_id, quantity, price_at_purchase
`

type CreateOrderItemParams struct {
	OrderID         pgtype.UUID    `json:"order_id"`
	VariantID       pgtype.UUID    `json:"variant_id"`
	Quantity        int32          `json:"quantity"`
	PriceAtPurchase pgtype.Numeric `json:"price_at_purchase"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	var i OrderItems
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.PriceAtPurchase,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (order_id, razorpay_payment_id, razorpay_signature, status, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, razorpay_payment_id, razorpay_signature, status, amount, verified_at
`

type CreatePaymentParams struct {
	OrderID           pgtype.UUID    `json:"order_id"`
	RazorpayPaymentID string         `json:"razorpay_payment_id"`
	RazorpaySignature string         `json:"razorpay_signature"`
	Status            string         `json:"status"`
	Amount            pgtype.Numeric `json:"amount"`
}

// ============================================================================
// Payments
// ============================================================================
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.RazorpayPaymentID,
		arg.RazorpaySignature,
		arg.Status,
		arg.Amount,
	)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RazorpayPaymentID,
		&i.RazorpaySignature,
		&i.Status,
		&i.Amount,
		&i.VerifiedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one

INSERT INTO shipments (order_id, courier_name, tracking_number, status)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, courier_name, tracking_number, status, shipped_at
`

type CreateShipmentParams struct {
	OrderID        pgtype.UUID `json:"order_id"`
	CourierName    string      `json:"courier_name"`
	TrackingNumber string      `json:"tracking_number"`
	Status         string      `json:"status"`
}

// ============================================================================
// Shipments
// ============================================================================
func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipments, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.OrderID,
		arg.CourierName,
		arg.TrackingNumber,
		arg.Status,
	)
	var i Shipments
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CourierName,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (name, email, password_hash, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, phone, created_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Phone        pgtype.Text `json:"phone"`
}

// queries.sql
// ============================================================================
// Users
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, line1, line2, city, state, pincode, is_default, created_at FROM addresses
WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id pgtype.UUID) (Addresses, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Addresses
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, address_id, status, total_amount, razorpay_order_id, created_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressID,
		&i.Status,
		&i.TotalAmount,
		&i.RazorpayOrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByRazorpayOrderID = `-- name: GetOrderByRazorpayOrderID :one
SELECT id, user_id, address_id, status, total_amount, razorpay_order_id, created_at FROM orders
WHERE razorpay_order_id = $1
`

func (q *Queries) GetOrderByRazorpayOrderID(ctx context.Context, razorpayOrderID string) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderByRazorpayOrderID, razorpayOrderID)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressID,
		&i.Status,
		&i.TotalAmount,
		&i.RazorpayOrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT oi.id, oi.order_id, oi.variant_id, oi.quantity, oi.price_at_purchase, pv.variant_name, pv.sku, p.name AS product_name
FROM order_items oi
JOIN product_variants pv ON oi.variant_id = pv.id
JOIN products p ON pv.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	ID              pgtype.UUID    `json:"id"`
	OrderID         pgtype.UUID    `json:"order_id"`
	VariantID       pgtype.UUID    `json:"variant_id"`
	Quantity        int32          `json:"quantity"`
	PriceAtPurchase pgtype.Numeric `json:"price_at_purchase"`
	VariantName     string         `json:"variant_name"`
	Sku             string         `json:"sku"`
	ProductName     string         `json:"product_name"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Quantity,
			&i.PriceAtPurchase,
			&i.VariantName,
			&i.Sku,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, description, price, images, is_active, created_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Products, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Images,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getShipmentsByOrderID = `-- name: GetShipmentsByOrderID :many
SELECT id, order_id, courier_name, tracking_number, status, shipped_at FROM shipments
WHERE order_id = $1
ORDER BY shipped_at DESC
`

func (q *Queries) GetShipmentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Shipments, error) {
	rows, err := q.db.Query(ctx, getShipmentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipments
	for rows.Next() {
		var i Shipments
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CourierName,
			&i.TrackingNumber,
			&i.Status,
			&i.ShippedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, phone, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, phone, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, variant_name, stock_quantity, sku, created_at FROM product_variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id pgtype.UUID) (ProductVariants, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i ProductVariants
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.StockQuantity,
		&i.Sku,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantByIDForUpdate = `-- name: GetVariantByIDForUpdate :one
SELECT pv.id, pv.product_id, pv.variant_name, pv.stock_quantity, pv.sku, pv.created_at, p.price, p.name AS product_name
FROM product_variants pv
JOIN products p ON pv.product_id = p.id
WHERE pv.id = $1
FOR UPDATE
`

type GetVariantByIDForUpdateRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	VariantName   string             `json:"variant_name"`
	StockQuantity int32              `json:"stock_quantity"`
	Sku           string             `json:"sku"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Price         pgtype.Numeric     `json:"price"`
	ProductName   string             `json:"product_name"`
}

func (q *Queries) GetVariantByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetVariantByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVariantByIDForUpdate, id)
	var i GetVariantByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.StockQuantity,
		&i.Sku,
		&i.CreatedAt,
		&i.Price,
		&i.ProductName,
	)
	return i, err
}

const getVariantByProductSlug = `-- name: GetVariantByProductSlug :one
SELECT pv.id, pv.product_id, pv.variant_name, pv.stock_quantity, pv.sku, pv.created_at, p.price, p.name AS product_name
FROM product_variants pv
JOIN products p ON pv.product_id = p.id
WHERE p.slug = $1
LIMIT 1
`

type GetVariantByProductSlugRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	VariantName   string             `json:"variant_name"`
	StockQuantity int32              `json:"stock_quantity"`
	Sku           string             `json:"sku"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Price         pgtype.Numeric     `json:"price"`
	ProductName   string             `json:"product_name"`
}

func (q *Queries) GetVariantByProductSlug(ctx context.Context, slug string) (GetVariantByProductSlugRow, error) {
	row := q.db.QueryRow(ctx, getVariantByProductSlug, slug)
	var i GetVariantByProductSlugRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.StockQuantity,
		&i.Sku,
		&i.CreatedAt,
		&i.Price,
		&i.ProductName,
	)
	return i, err
}

const getVariantByProductSlugForUpdate = `-- name: GetVariantByProductSlugForUpdate :one
SELECT pv.id, pv.product_id, pv.variant_name, pv.stock_quantity, pv.sku, pv.created_at, p.price, p.name AS product_name
FROM product_variants pv
JOIN products p ON pv.product_id = p.id
WHERE p.slug = $1
LIMIT 1
FOR UPDATE
`

type GetVariantByProductSlugForUpdateRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	VariantName   string             `json:"variant_name"`
	StockQuantity int32              `json:"stock_quantity"`
	Sku           string             `json:"sku"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Price         pgtype.Numeric     `json:"price"`
	ProductName   string             `json:"product_name"`
}

func (q *Queries) GetVariantByProductSlugForUpdate(ctx context.Context, slug string) (GetVariantByProductSlugForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVariantByProductSlugForUpdate, slug)
	var i GetVariantByProductSlugForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantName,
		&i.StockQuantity,
		&i.Sku,
		&i.CreatedAt,
		&i.Price,
		&i.ProductName,
	)
	return i, err
}

const getVariantsByProductID = `-- name: GetVariantsByProductID :many
SELECT id, product_id, variant_name, stock_quantity, sku, created_at FROM product_variants
WHERE product_id = $1
ORDER BY variant_name ASC
`

func (q *Queries) GetVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductVariants, error) {
	rows, err := q.db.Query(ctx, getVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariants
	for rows.Next() {
		var i ProductVariants
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantName,
			&i.StockQuantity,
			&i.Sku,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProducts = `-- name: ListActiveProducts :many

SELECT id, slug, name, description, price, images, is_active, created_at FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
`

// ============================================================================
// Products & Variants
// ============================================================================
func (q *Queries) ListActiveProducts(ctx context.Context) ([]Products, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Images,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT id, user_id, line1, line2, city, state, pincode, is_default, created_at FROM addresses
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Addresses, error) {
	rows, err := q.db.Query(ctx, listAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Addresses
	for rows.Next() {
		var i Addresses
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, address_id, status, total_amount, razorpay_order_id, created_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Orders, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AddressID,
			&i.Status,
			&i.TotalAmount,
			&i.RazorpayOrderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateVariantStock = `-- name: UpdateVariantStock :exec
UPDATE product_variants
SET stock_quantity = $2
WHERE id = $1
`

type UpdateVariantStockParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) error {
	_, err := q.db.Exec(ctx, updateVariantStock, arg.ID, arg.StockQuantity)
	return err
}
