// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// Addresses
	// ============================================================================
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Addresses, error)
	// ============================================================================
	// Orders & OrderItems
	// ============================================================================
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error)
	// ============================================================================
	// Payments
	// ============================================================================
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error)
	// ============================================================================
	// Shipments
	// ============================================================================
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipments, error)
	// queries.sql
	// ============================================================================
	// Users
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	GetAddressByID(ctx context.Context, id pgtype.UUID) (Addresses, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Orders, error)
	GetOrderByRazorpayOrderID(ctx context.Context, razorpayOrderID string) (Orders, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsByOrderIDRow, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Products, error)
	GetShipmentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Shipments, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error)
	GetVariantByID(ctx context.Context, id pgtype.UUID) (ProductVariants, error)
	GetVariantByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetVariantByIDForUpdateRow, error)
	GetVariantByProductSlug(ctx context.Context, slug string) (GetVariantByProductSlugRow, error)
	GetVariantByProductSlugForUpdate(ctx context.Context, slug string) (GetVariantByProductSlugForUpdateRow, error)
	GetVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductVariants, error)
	// ============================================================================
	// Products & Variants
	// ============================================================================
	ListActiveProducts(ctx context.Context) ([]Products, error)
	ListAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Addresses, error)
	ListOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Orders, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) error
}

var _ Querier = (*Queries)(nil)
